---
# tasks file for roles/haproxy

- name: http
  package:
    name: httpie
    state: latest

- name: install HAProxy
  yum:
    name: haproxy
    state: latest

- name: enable HAProxy 
  service:
    name: haproxy
    state: started

- name: HAProxy template
  template:
    src: haproxy.cfg.j2
    dest: /tmp/haproxy.cfg

  notify: 
     - restart_haproxy


